config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products, except: :show

  resources :orders, only: [:update, :destroy] do
    member do
      #custom PUT actions (outside CRUD) for adding and remove products from the order
      put :add_to
      put :remove_from
    end
  end

  devise_for :users, :controllers => { registrations: 'registrations' }

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)


    user ||= User.new # guest user (not logged in)
    if user.admin == true
      can :manage, :all
    else
      can :read, Product
      can :manage, Order do |order|
        order.try(:user) == user
      end
    end
  end
end

app/models/computer.rb
class Computer < ActiveRecord::Base
  has_one :product, as: :category, dependent: :destroy
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :product_orders
  has_many :products, through: :product_orders, source: :product
  belongs_to :user

  # ensure there is only one active order per user
  validates_uniqueness_of :status, conditions: -> { where(status: 'active') }, scope: :user_id

  # calculate shopping cart total
  def calculate_total
    self.products.pluck(:price).inject(:+)
  end

  # count quantity for each product inside the cart and store it in a product => qty hash
  def items_counter
    cart = Hash.new(0)
    self.products.pluck(:id).each do |prod|
      cart[prod.to_s] += 1
    end
    return cart
  end

  # check stock for each item and adjust quantities in the cart if necessary
  def check_stocks
    # if the order is updated according to the stock, alert user and ask to chekcout again
    order_changed = "no_order_change"
    items_counter.each do |prod, qty|
      # if the quantity inside the cart is greaterthan the one in the stock, adjust the quantity in the cart
      product = Product.find(prod)
      diff = product.stock - qty
      if diff < 0
        # make diff positive
        diff.abs.times do
          ProductOrder.find_by(order: self, product: prod).destroy
        end
        order_changed = "order_changed"
      else
        update_stocks(product, qty)
      end
    end
    return order_changed
  end

  # update stock at checkout time
  def update_stocks(prod, qty)
    prod.update_attributes(stock: (prod.stock-qty))
  end

end

app/models/printer.rb
class Printer < ActiveRecord::Base
  has_one :product, as: :category, dependent: :destroy
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :product_orders
  has_many :orders, through: :product_orders, source: :order
  belongs_to :category, polymorphic: true, dependent: :destroy

  validates_presence_of :price, :stock

  # #convert all categories to upper case
  # before_save do
  #   self.category.upcase!
  # end
end

app/models/product_order.rb
class ProductOrder < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  #register the admin usert that added the product
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to products_path, notice: "You are not authorized to access this area"
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order
  before_action :set_product, except: :update
  load_and_authorize_resource through: :current_user

  # add products to order
  def add_to
    @order.products << @product

    respond_to do |format|
      if @order.save
        format.html{redirect_to products_path(category: @product.category), notice: "Product added to cart"}
      else
        format.html{redirect_to products_path(category: @product.category), notice: "Something went wrong, please try again"}
      end
    end
  end

  # remove products from order
  def remove_from
    remove = ProductOrder.find_by(order: @order, product: @product)
    respond_to do |format|
      if remove.destroy
        format.html{redirect_to products_path(category: @product.category), notice: "Product removed from cart"}
      else
        format.html{redirect_to products_path(category: @product.category), notice: "Something went wrong, please try again"}
      end
    end
  end

  # checkout the order and update the stocks
  def update
    respond_to do |format|
      if @order.check_stocks == "order_changed"
        format.html{redirect_to products_path, notice: "Please check your order! Products were updated according to the current stocks."}
      else
        @order.update_attributes(status: "checkout")
        format.html{redirect_to products_path, notice: "Your order will be shipped"}
      end
    end
  end

  # destroy the current order
  def destroy
    respond_to do |format|
      if @order.destroy
        format.html{redirect_to products_path, notice: "Cart deleted"}
      else
        format.html{redirect_to products_path, notice: "Something went wrong, please try again"}
      end
    end
  end

  private
    def order_params
      params.require(:product).permit(:status)
    end

    def set_order
      @order = Order.find(params[:id])
    end

    def set_product
      @product = Product.find(params[:product]) if params[:product]
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]
  # cancancan authorization
  load_and_authorize_resource through: :current_user

  def index
    shopping_cart = ShoppingCart.new(user: current_user, params: params)
    @categories = shopping_cart.product_categories
    @products = shopping_cart.products_by_category
    @order = shopping_cart.current_order
  end

  def new
    @product = Product.new
  end

  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html{redirect_to products_path(category: @product.category), notice: "Product created"}
      else
        format.html{render "new", notice: "Something went wrong, please try again"}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html{redirect_to products_path(category: @product.category), notice: "Product updated"}
      else
        format.html{render "edit", notice: "Something went wrong, please try again"}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @product.destroy
        format.html{redirect_to products_path(category: @product.category), notice: "Product deleted"}
      else
        format.html{redirect_to products_path(category: @product.category), notice: "Something went wrong, please try again"}
      end
    end
  end

  private
    def product_params
      params.require(:product).permit(:name, :price, :stock, :category)
    end

    def set_product
      @product = Product.find(params[:id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/computers/_computer.html.slim
.h3 = computer.name
p
  | CPU : #{computer.cpu}
p
  | Memory : #{computer.memory}
  

app/views/layouts/_topmenu.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed data-target="#cls-top-bar" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "TEST SHOP", root_path, class: "navbar-brand"
    #cls-top-bar.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if current_user

          li.dropdown
            a.dropdown-toggle aria-expanded="false" data-toggle="dropdown" href="#" role="button"
              = gravatar_tag current_user.email, size: 24
              | &nbsp
              = current_user.name
              span.caret
            ul.dropdown-menu role="menu"
              li
                = link_to "Settings", edit_user_registration_path
              li.divider
              li
                = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          li
            = link_to "Login", new_user_session_path
    /! /.navbar-collapse
  /! /.container-fluid

app/views/layouts/application.html.slim
doctype html
html
  head
    title Test Shop
    = stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tags
    // if IE is  < v9 include javascript
    /![if lt IE 9]
      | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>

  body
  
  = render "layouts/topmenu"
  
  - flash.each do |type, message|
    .alert.alert-info.fade-in
      button.close data-dismiss="alert" x
      = message
  .container-fluid
    = yield

app/views/products/_form.html.slim
= simple_form_for @product do |f|
  = f.error_notification
  = f.input :name, required: true, label: false, placeholder: "product name", input_html: {class: "form-control"}
  = f.input :price, required: true, label: false, placeholder: "unit price", input_html: {class: "form-control"}
  = f.input :stock, required: true, label: false, placeholder: "available units in stock", input_html: {class: "form-control"}
  = f.input :category, required: true, label: false, placeholder: "product category", input_html: {class: "form-control"}
  = f.button :submit, class: "btn btn-primary btn-block"

app/views/products/_product.html.slim
.col-md-6
  .panel.panel-default
    .panel-heading.small
      = product.stock
      |  available in stock  
    .panel-body
      = render product.category
      p
        | price:  
        = product.price
    .panel-footer.clearfix
      - if current_user.admin
        .col-md-6
          = link_to "EDIT", edit_product_path(product), class: "btn btn-warning btn-block"
        .col-md-6
          = link_to "DELETE", product_path(product), class: "btn btn-danger btn-block", 
                                                data: { confirm: "Are you sure?" }, 
                                                method: :delete
      - else
        = link_to "ADD TO CART", add_to_order_path(@order, product: product), 
                          class: "btn btn-primary btn-block btn-xs #{'disabled' if product.stock == 0}",             
                          method: :put

app/views/products/edit.html.slim
h3 EDIT PRODUCT
= render "form"

app/views/products/index.html.slim
.row
  .col-md-2
    h3.text-center CATEGORIES
    
    .btn-group-vertical
      // Send product category as param to index
      // Activate the button for the current category
      - @categories.each do |cat|
        = link_to cat.upcase, products_path(category: cat), 
          class: "btn btn-default #{'active' if @products.first.category == cat}", 
          type: "button"


  .col-md-5
    h3.text-center PRODUCTS
    
    - if current_user.admin
      = link_to "ADD NEW PRODUCT", new_product_path, class: "btn btn-primary"
    p   
    .row
      = render @products      
      
  - if !current_user.admin    
    .col-md-5
      h3.text-center SHOPPING CART
      .col-md-6 
        strong PRODUCT
      .col-md-3.text-right 
        strong PRICE
      - @order.products.each do |prod|
        .col-md-6 = prod.name
        .col-md-3.text-right = prod.price
        .col-md-3
          = link_to "REMOVE", remove_from_order_path(@order, product: prod), 
                                                  class: "btn btn-xs btn-danger btn-block",
                                                  method: :put
        .col-md-12
    
      .col-md-6 
        strong TOTAL
      .col-md-3.text-right 
        strong = @order.calculate_total
      .col-md-3
      .col-md-12
        p  
      .col-md-8
        = link_to "CHECKOUT", order_path(@order), 
          class: "btn btn-primary btn-block #{'disabled' if @order.products.size == 0}",
          method: :put
      .col-md-4
        = link_to "DELETE CART", order_path(@order), 
          class: "btn btn-danger btn-block #{'disabled' if @order.products.size == 0}", 
          data: { confirm: "Are you sure?" }, 
          method: :delete

app/views/products/new.html.slim
h3 CREATE NEW PRODUCT
= render "form"